-- Utilisateur admin
INSERT INTO UTILISATEURS (ID, USERNAME, PASSWORD, ROLE, NOM, PRENOM, EMAIL, IS_ACTIVE, AUTHORITIES, IS_NOT_LOCKED, LAST_LOGIN_DATE, JOIN_DATE)
VALUES ('U001', 'admin', 'adminpass', 'ROLE_ADMIN', 'Admin', 'Root', 'admin@example.com', TRUE, 'READ,WRITE', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Evenement
INSERT INTO EVENEMENTS (NOM, DESCRIPTION, IMAGE, DUREE, NBE_JOUEUR_MAX, PRIX, DIFFICULTE)
VALUES ('Escape Room Zombie', 'Survivez à une attaque de zombies', 'zombie.jpg', 60, 6, 80, 'DIFFICILE');

-- TimeSlot (correct table name CRENEAU_HORAIRE)
INSERT INTO CRENEAU_HORAIRE (DATE, HEURE_DEBUT, HEURE_FIN)
VALUES ('2025-07-01', '14:00:00', '15:00:00');

-- Réservation (table RESERVATIONS, colonnes conformes)
INSERT INTO RESERVATIONS (ID_USER, ID_EVENEMENT, ID_CRENEAU_HORAIRE, DATE_RESERVATION, MONTANT, MONTANT_HT, MONTANT_TVA, NUMERO_RESERVATION)
VALUES (1, 1, 1, CURRENT_TIMESTAMP, 320.00, 266.67, 53.33, 'RES12345');
