CREATE TABLE UTILISATEURS (
    ID_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50),
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    EMAIL VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    AUTHORITIES VARCHAR(255),
    IS_NOT_LOCKED BOOLEAN,
    LAST_LOGIN_DATE TIMESTAMP,
    JOIN_DATE TIMESTAMP
);
