CREATE TABLE UTILISATEURS (
    ID_USER BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50),
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    EMAIL VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    AUTHORITIES VARCHAR(255),
    IS_NOT_LOCKED BOOLEAN,
    LAST_LOGIN_DATE TIMESTAMP,
    JOIN_DATE TIMESTAMP
);

CREATE TABLE EVENEMENTS (
    ID_EVENEMENT BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255),
    DESCRIPTION TEXT,
    IMAGE VARCHAR(255),
    DUREE INT,
    NBE_JOUEUR_MAX INT,
    PRIX INT,
    DIFFICULTE VARCHAR(50)
);

CREATE TABLE CRENEAU_HORAIRE (
    ID_CRENEAU_HORAIRE BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE DATE,
    HEURE_DEBUT TIME,
    HEURE_FIN TIME
);

CREATE TABLE RESERVATIONS (
    ID_RESERVATION BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_RESERVATION VARCHAR(255),
    DATE_RESERVATION TIMESTAMP,
    MONTANT DECIMAL(15,2),
    MONTANT_HT DECIMAL(15,2),
    MONTANT_TVA DECIMAL(15,2),
    ID_USER BIGINT,
    ID_EVENEMENT BIGINT,
    ID_CRENEAU_HORAIRE BIGINT,
    ID_PAIEMENT BIGINT,
    FOREIGN KEY (ID_USER) REFERENCES UTILISATEURS(ID_USER),
    FOREIGN KEY (ID_EVENEMENT) REFERENCES EVENEMENTS(ID_EVENEMENT),
    FOREIGN KEY (ID_CRENEAU_HORAIRE) REFERENCES CRENEAU_HORAIRE(ID_CRENEAU_HORAIRE)
);
